# -*- coding: utf-8 -*-
"""Render only the municipality pages. Keep the site's shared header/footer intact."""
from pathlib import Path
import json,re,html
ROOT=Path(__file__).resolve().parent.parent
D=json.loads((ROOT/'content/municipal-cup.json').read_text())
for idx,lang in enumerate(['ru','et','en']):
 def t(ru,et,en):return [ru,et,en][idx]
 def esc(v):return html.escape(str(v),quote=True)
 base='/narva-joesuu-winter-fest'
 pref=base+('' if lang=='ru' else '/'+lang)
 def image(name,cls=''):
  return f'<img class="{cls}" src="{base}/assets/{name}" alt="" loading="lazy" width="160" height="160">'
 def link(route,label,cls='text-link'):
  return f'<a class="{cls}" href="{pref+route}">{label}<span aria-hidden="true">↗</span></a>'
 def pending():return t('Уточняется','Täpsustamisel','To be confirmed')
 def acc(title,body,ident=''):
  return f'<details class="mc-accordion"'+(f' id="{ident}"' if ident else '')+f'><summary>{title}<span aria-hidden="true">+</span></summary><div class="mc-answer">{body}</div></details>'
 def para(s):return f'<p>{s}</p>'
 nav=[('overview',t('Главное','Ülevaade','Overview')),('team',t('Команда','Võistkond','Team')),('sports',t('Дисциплины','Alad','Sports')),('day',t('Программа дня','Päevakava','The day')),('registration',t('Стоимость и запись','Hind ja registreerimine','Fees & entry')),('practical',t('Практическое','Praktiline info','Practical info')),('rules',t('Регламенты','Juhendid','Rules'))]
 cards=''
 for s in D['disciplines']:
  pdf=s['rulesPdf'].get(lang)
  download=f'<a href="{esc(pdf)}" target="_blank" rel="noopener">{t("Регламент PDF","Juhend PDF","Rules PDF")} ↗</a>' if pdf else f'<span class="mc-muted">{t("Регламент готовится","Juhend on koostamisel","Rules are being prepared")}</span>'
  fields=[t('Формат и участники','Formaat ja osalejad','Format and participants'),t('Задание и подсчёт очков','Ülesanne ja punktiarvestus','Task and scoring'),t('Инвентарь и безопасность','Varustus ja ohutus','Equipment and safety')]
  cards+=f'''<details class="mc-sport" id="sport-{s['id']}" data-sport-group="{s['group']}"><summary>{image(s['icon'])}<span class="mc-sport-name">{s['name'][idx]}</span><span class="mc-sport-note">{s['note'][idx]}</span><span class="mc-sport-more">{t('Описание и правила','Kirjeldus ja reeglid','Details and rules')}<b aria-hidden="true">+</b></span></summary><div class="mc-sport-body"><p>{t('Дисциплина в предварительной программе. Формат этапа и условия участия ещё не утверждены.','Ala on esialgses programmis. Etapi formaat ja osalemistingimused ei ole veel kinnitatud.','This discipline is in the provisional programme. Its format and entry conditions are not yet confirmed.')}</p><dl>{''.join(f'<div><dt>{f}</dt><dd>{pending()}</dd></div>' for f in fields)}</dl>{download}</div></details>'''
 fees=t('Стоимость будет объявлена','Osalustasu avaldame peagi','Entry fee to be announced') if D['priceEurPerTeam'] is None else str(D['priceEurPerTeam'])+' €'
 teamSize=pending() if D['teamSize'] is None else str(D['teamSize'])
 intro=t('Представьте свой<br>город или волость','Esinda oma<br>linna või valda','Represent your<br>city or municipality')
 lead=t('Winter Cup объединяет команды самоуправлений в спортивных испытаниях на зимнем берегу Нарва-Йыэсуу. Общий результат складывается из работы всей команды.','Winter Cup toob omavalitsuste võistkonnad Narva-Jõesuu talvisele rannale sportlikes katsetes võistlema. Ühine tulemus sünnib kogu võistkonna koostööst.','Winter Cup brings municipal teams together for sporting challenges on the winter coast of Narva-Jõesuu. The shared result comes from the whole team’s effort.')
 eligibility=[(t('Кто может представлять самоуправление?','Kes võib omavalitsust esindada?','Who can represent a municipality?'),t('Категория предназначена для городских и волостных самоуправлений. Требования к связи участника с самоуправлением — место работы, проживания или иной критерий — будут определены в общем регламенте.','Kategooria on mõeldud linnadele ja valdadele. Nõutav seos omavalitsusega — töökoht, elukoht või muu alus — määratakse üldjuhendis.','This category is for cities and municipalities. The required connection — employment, residence or another criterion — will be defined in the general rules.')),(t('Сколько человек и команд можно заявить?','Mitu osalejat ja võistkonda saab registreerida?','How many people and teams may enter?'),t('Размер команды, запасные участники, возрастные требования и число команд от одного самоуправления уточняются. Не нужно собирать окончательный состав до публикации этих условий.','Võistkonna suurus, varuliikmed, vanusenõuded ja ühe omavalitsuse võistkondade arv täpsustuvad. Lõpliku koosseisu saab paika panna pärast tingimuste avaldamist.','Team size, substitutes, age requirements and the number of teams per municipality are being confirmed. Finalise your roster once these conditions are published.')),(t('Как представить свой город или волость?','Kuidas oma linna või valda esindada?','How can we represent our municipality?'),t('Подумайте об общем названии команды, цветах и флаге. Порядок представления самоуправлений, использование символики и формат награждения появятся в программе.','Mõelge ühisele võistkonnanimele, värvidele ja lipule. Omavalitsuste tutvustamise, sümboolika kasutamise ja autasustamise korraldus avaldatakse programmis.','Consider a shared team name, colours and a flag. Arrangements for municipal introductions, use of symbols and the award ceremony will be published in the programme.'))]
 phases=[(t('Приезд и встреча команды','Saabumine ja võistkonna vastuvõtt','Arrival and check-in'),t('Регистрация на месте, знакомство с площадкой и инструктаж.','Kohapealne registreerimine, alaga tutvumine ja juhendamine.','Check-in, venue orientation and briefing.')),(t('Командные испытания','Võistkondlikud katsed','Team challenges'),t('Прохождение дисциплин и перерывы между этапами.','Alade läbimine ja pausid etappide vahel.','Sporting challenges with breaks between stages.')),(t('Питание и отдых','Toitlustus ja puhkus','Food and rest'),t('Питание входит в стоимость участия. Время и место выдачи сообщим отдельно.','Toitlustus sisaldub osalustasus. Aja ja koha teatame eraldi.','Food is included in the entry fee. Serving times and location will be announced.')),(t('Общий результат','Ühine tulemus','The team result'),t('Подведение итогов и награждение. Формат уточняется.','Kokkuvõtted ja autasustamine. Formaat täpsustub.','Results and awards. Format to be confirmed.'))]
 practical=[(t('Питание','Toitlustus','Food'),t('Включено в стоимость участия. Меню, порции, время и порядок учёта аллергий и особого питания будут опубликованы здесь.','Sisaldub osalustasus. Menüü, portsjonid, ajad ning allergiate ja eritoitumise arvestamise kord avaldatakse siin.','Included in the entry fee. Menu, portions, serving times and dietary arrangements will be published here.')),(t('Дорога, парковка и автобус команды','Kohalesõit, parkimine ja võistkonna buss','Travel, parking and team buses'),t('Место проведения — Нарва-Йыэсуу. Точка высадки, парковка автобусов, точный вход и схема площадки уточняются.','Toimumiskoht on Narva-Jõesuu. Mahasõidukoht, busside parkimine, sissepääs ja ala plaan täpsustuvad.','The event takes place in Narva-Jõesuu. Drop-off, bus parking, the entrance and venue map are being confirmed.')+link('/visit/travel/',t('Как добраться','Kuidas kohale jõuda','Getting here'))),(t('Одежда, инвентарь и раздевалки','Riietus, varustus ja riietusruumid','Clothing, equipment and changing'),t('Планируйте одежду для активного дня на улице, тёплый слой для перерывов и сменные вещи. Перечень предоставляемого инвентаря, раздевалки и хранение вещей уточняются.','Valige riided aktiivseks õuepäevaks, soe lisakiht pausideks ja vahetusriided. Kohapealse varustuse, riietusruumide ja asjade hoidmise info täpsustub.','Plan clothing for an active outdoor day, a warm layer for breaks and a change of clothes. Supplied equipment, changing facilities and storage are being confirmed.')),(t('Доступность и помощь на площадке','Ligipääsetavus ja abi kohapeal','Accessibility and on-site help'),t('Если участнику нужны особые условия, заранее напишите организатору. Информация о доступных маршрутах, помощи на площадке и действиях при изменении погоды будет в памятке участника.','Kui osaleja vajab eritingimusi, kirjutage korraldajale ette. Ligipääsetavate liikumisteede, kohapealse abi ja ilmamuutuste info avaldatakse osaleja meelespeas.','Contact the organiser ahead of time about any access requirements. Accessible routes, on-site support and weather contingency information will be included in the participant guide.')),(t('Проживание и сопровождающие','Majutus ja kaasatulijad','Accommodation and supporters'),t('Проживание и дорогу планируйте отдельно. На фестиваль можно приехать с болельщиками: вход на общую площадку свободный. Условия питания сопровождающих уточняются.','Planeerige majutus ja transport eraldi. Kaasa võib võtta toetajaid: sissepääs festivali üldalale on tasuta. Kaasatulijate toitlustustingimused täpsustuvad.','Arrange accommodation and travel separately. Supporters are welcome: entry to the general festival site is free. Catering arrangements for accompanying guests are being confirmed.')+link('/visit/stay/',t('Где остановиться','Kus ööbida','Where to stay')))]
 rules=[(t('Участники и состав команды','Osalejad ja võistkonna koosseis','Eligibility and team composition'),t('Критерии представительства, возраст, размер команды, запасные и замены.','Esindamise tingimused, vanus, võistkonna suurus, varuliikmed ja vahetused.','Representation criteria, age, team size, substitutes and changes.')),(t('Общий зачёт и результаты','Üldarvestus ja tulemused','Overall scoring and results'),t('Начисление очков, равенство результатов, пропуск этапа и порядок награждения.','Punktiarvestus, viigid, etapi vahelejätmine ja autasustamine.','Points, ties, missed stages and awards.')),(t('Судейство и обращения','Kohtunikud ja pöördumised','Officials and queries'),t('Контакт главного судьи, порядок и сроки подачи обращений по результатам.','Peakohtuniku kontakt ning tulemusi puudutavate pöördumiste kord ja tähtajad.','Head official contact and the process and deadlines for result queries.')),(t('Изменения, отмена и безопасность','Muudatused, tühistamine ja ohutus','Changes, cancellation and safety'),t('Погодные изменения, замена дисциплин, отмена участия, возвраты и требования безопасности.','Ilmast tingitud muudatused, alade asendamine, osalemise tühistamine, tagastused ja ohutusnõuded.','Weather changes, replacement disciplines, withdrawal, refunds and safety requirements.'))]
 checks=[t('Выбрать ответственного и капитана','Valida kontaktisik ja kapten','Choose a coordinator and captain'),t('Проверить состав по утверждённому регламенту','Kontrollida koosseisu kinnitatud juhendi järgi','Check the roster against the approved rules'),t('Согласовать бюджет и реквизиты плательщика','Kooskõlastada eelarve ja maksja andmed','Agree the budget and billing details'),t('Зарегистрировать команду в Fienta','Registreerida võistkond Fientas','Register the team in Fienta'),t('Спланировать транспорт и сообщить о питании','Planeerida transport ja teatada toitumisvajadustest','Plan transport and communicate dietary needs'),t('Передать участникам программу и регламенты','Jagada osalejatele kava ja juhendeid','Share the schedule and rules with participants')]
 # Keep approved conditions in sync with the published regulation.
 sections=re.split(r'^## ',(ROOT/f'content/municipal-rules/{lang}.md').read_text(),flags=re.M)[1:]
 bodies=[part.split('\n',1)[1].strip().split('\n\n') for part in sections]
 eligibility=[(t('Кто может участвовать?','Kes võivad osaleda?','Who may participate?'),' '.join(bodies[1][:2])),(t('Состав и число команд','Koosseis ja võistkondade arv','Team size and number of teams'),' '.join(bodies[1][2:])),(t('Флаг и парад самоуправлений','Lipp ja omavalitsuste paraad','Flags and municipal parade'),bodies[4][-1])]
 phases=[(t('Встреча и инструктаж','Saabumine ja juhendamine','Arrival and briefing'),bodies[0][1]),(t('Испытания по графику команды','Katsed võistkonna ajakava järgi','Your team’s challenge schedule'),bodies[4][0]),(t('Питание и отдых','Toitlustus ja puhkus','Food and rest'),t('Два приёма пищи для пяти участников включены. Время питания и отдыха указано в графике вашей команды.','Hinnas on kaks toidukorda viiele osalejale. Toitlustuse ja puhkuse ajad on võistkonna ajakavas.','Two meals for five participants are included. Meal and rest times are set in your team’s schedule.')),(t('Парад и награждение','Paraad ja autasustamine','Parade and awards'),bodies[4][-1])]
 practical[0]=(practical[0][0],phases[2][1])
 practical[2]=(practical[2][0],bodies[3][-2]+' '+bodies[3][-1])
 practical[4]=(practical[4][0],t('Дорогу и проживание самоуправление организует отдельно. Питание сопровождающих в стоимость команды не входит.','Transpordi ja majutuse korraldab omavalitsus eraldi. Kaasatulijate toitlustus ei sisaldu võistkonna hinnas.','The municipality arranges transport and accommodation separately. Meals for accompanying guests are not included in the team fee.'))
 rules=[(t('Состав и замены','Koosseis ja vahetused','Roster and replacements'),bodies[2][1]+' '+bodies[2][2]),(t('Результаты и равенство очков','Tulemused ja viigid','Results and ties'),' '.join(bodies[5])),(t('Обращения по результатам','Pöördumised tulemuste kohta','Result queries'),' '.join(bodies[6][1:])),(t('Отмена, перенос и отказ','Tühistamine, edasilükkamine ja loobumine','Cancellation, postponement and withdrawal'),' '.join(bodies[7]))]
 fees=t('От 90 € за команду','Alates 90 € võistkonnale','From €90 per team')
 priceTable='<table class="mc-fee-table">'+''.join('<tr><td>'+a+'</td><td>'+b+'</td></tr>' for a,b in [('≤ 31.12.2026','90 €'),('01–10.01.2027','120 €'),('11–17.01.2027','150 €')])+'</table>'
 checks=[checks[0],checks[2],t('Подать заявку в Fienta и оплатить счёт','Esitada taotlus Fientas ja tasuda arve','Apply on Fienta and pay the invoice'),t('До 19 января отправить имена и места работы пяти участников','Saata 19. jaanuariks viie osaleja nimed ja töökohad','Send five participants’ names and workplaces by 19 January'),checks[4],checks[5]]
 pdf=D['rulesPdf'].get(lang)
 rulesLink=f'<a class="button" href="{esc(pdf)}" target="_blank" rel="noopener">{t("Общий регламент PDF","Üldjuhend PDF","General rules PDF")} ↗</a>' if pdf else f'<p class="mc-doc-status">{t("Общий регламент и PDF пока не опубликованы","Üldjuhend ja PDF ei ole veel avaldatud","General rules and PDF have not been published yet")}</p>'
 rulesLink=link('/winter-cup/municipalities/rules/',t('Читать общий регламент','Loe üldjuhendit','Read the general rules'),'button')+rulesLink
 out=f'''<main id="main" class="municipal-page">

 <section class="mc-hero" id="overview"><div class="mc-hero-copy"><h1>{intro}</h1><div class="mc-actions"><a class="button" href="#registration">{t('Участие и стоимость','Osalemine ja hind','Entry and fees')}<span aria-hidden="true">↗</span></a><a class="mc-inline" href="#sports">{t('Посмотреть дисциплины','Vaata alasid','Explore the sports')}</a></div></div><div class="mc-hero-visual"><img class="mc-photo" src="{base}/assets/cup-1600.webp" srcset="{base}/assets/cup-800.webp 800w, {base}/assets/cup-1600.webp 1600w" sizes="(max-width:760px) 100vw,55vw" width="1672" height="941" alt="{t('Командная игра на зимнем берегу','Võistkonnamäng talvisel rannal','Team sport on the winter coast')}" fetchpriority="high"><div class="mc-date"><strong>22.01</strong><span>{t('ПЯТНИЦА','REEDE','FRIDAY')} · 2027</span></div>{image('cup-municipality-ribbon.png','mc-hero-object')}</div></section>
 <div class="mc-facts"><div><span>{t('Место','Asukoht','Location')}</span><strong>Narva-Jõesuu</strong></div><div><span>{t('Участники','Osalejad','Participants')}</span><strong>{t('Города и волости','Linnad ja vallad','Cities and municipalities')}</strong></div><div><span>{t('Питание','Toitlustus','Food')}</span><strong>{t('Входит в цену','Hinnas','Included')}</strong></div><div><span>{t('Программа дня','Päevakava','Day programme')}</span><strong>~11:00–19:00</strong></div></div>
 <nav class="mc-jump" aria-label="{t('На этой странице','Sellel lehel','On this page')}">{''.join(f'<a href="#{a}">{b}</a>' for a,b in nav)}</nav>
 <section class="mc-section mc-team" id="team"><div><h2>{t('Ваш город<br>Ваша команда','Teie omavalitsus<br>Teie võistkond','Your community<br>Your team')}</h2><p>{bodies[1][0]}</p><div class="mc-team-size"><span>{t('Размер команды','Võistkonna suurus','Team size')}</span><strong>{teamSize}</strong></div></div><div>{''.join(acc(a,para(b)) for a,b in eligibility)}</div></section>
 <section class="mc-section mc-sports-section" id="sports"><div class="mc-section-head"><div><h2>{t('Разные игры<br>Общий результат','Erinevad alad<br>Ühine tulemus','Different challenges<br>One team result')}</h2><p>{t('Предварительно — 6 дисциплин. Окончательный список и правила утвердим отдельно.','Esialgu on kavas 6 ala. Lõpliku valiku ja reeglid kinnitame eraldi.','Six disciplines are provisionally planned. The final list and rules will be confirmed separately.')}</p></div><span class="mc-status">{t('Предварительная программа','Esialgne programm','Provisional programme')}</span></div><div class="mc-filters" role="group" aria-label="{t('Фильтр дисциплин','Alade filter','Filter disciplines')}">{''.join(f'<button type="button" data-mc-filter="{k}" aria-pressed="{str(k=="all").lower()}">{v}</button>' for k,v in [('all',t('Все дисциплины','Kõik alad','All disciplines')),('movement',t('Движение','Liikumine','Movement')),('precision',t('Точность','Täpsus','Precision')),('team',t('Командная игра','Võistkonnamäng','Team play'))])}</div><p class="sr-only" id="mc-filter-status" role="status" data-label="{t('Дисциплин','Alasid','Disciplines')}"></p><div class="mc-sport-grid">{cards}</div></section>
 <section class="mc-section" id="day"><div class="mc-section-head"><h2>{t('Как пройдёт пятница','Reedese päeva plaan','Your Friday')}</h2><p>{bodies[0][1]}</p></div><div class="mc-day-grid">{''.join(f'<article><span class="mc-day-dot" aria-hidden="true"></span><h3>{a}</h3><p>{b}</p></article>' for a,b in phases)}</div></section>
 <section class="mc-registration" id="registration"><div class="mc-price"><p class="mc-kicker">{t('УЧАСТИЕ КОМАНДЫ','VÕISTKONNA OSALEMINE','TEAM ENTRY')}</p><h2>{t('Соберите своих','Pange tiim kokku','Bring your team')}</h2><p class="mc-price-value">{fees}</p>{priceTable}<p>{bodies[3][2]}</p><div class="mc-included">{image('12-thermos.webp')}<div><strong>{t('Питание включено','Toitlustus sisaldub hinnas','Food is included')}</strong><span>{t('для участников команды','võistkonna osalejatele','for team participants')}</span></div></div><a class="button button-light" data-registration="municipalities" href="https://fienta.com/{lang}">{t('Регистрация в Fienta','Registreeru Fientas','Register on Fienta')}<span aria-hidden="true">↗</span></a><p class="mc-price-note">{t('Заявки до 17 января · состав до 19 января','Taotlused 17. jaanuarini · koosseis 19. jaanuariks','Applications by 17 January · roster by 19 January')}</p></div><div class="mc-registration-copy"><h3>{t('От решения — к старту','Otsusest stardini','From decision to start')}</h3><ol><li><strong>{t('Назначьте ответственного','Määrake kontaktisik','Choose a coordinator')}</strong><p>{t('Он будет собирать состав и получать организационную информацию.','Tema koondab võistkonna ja võtab vastu korraldusinfo.','They will coordinate the roster and event information.')}</p></li><li><strong>{t('Проверьте условия участия','Kontrollige osalemistingimusi','Check entry conditions')}</strong><p>{t('Пять участников от 18 лет. Связь с самоуправлением — работа или членство в собрании.','Viis vähemalt 18-aastast osalejat. Seos omavalitsusega: töökoht või volikogu liikmesus.','Five participants aged 18+. Eligibility is based on employment or council membership.')}</p></li><li><strong>{t('Оформите регистрацию','Vormistage registreerimine','Complete registration')}</strong><p>{bodies[2][0]}</p></li></ol>{acc(t('Нужен счёт для самоуправления?','Kas omavalitsus vajab arvet?','Does your municipality need an invoice?'),para(bodies[3][2])+'<a href="mailto:info@winterfest.ee">info@winterfest.ee ↗</a>')}</div></section>
 <section class="mc-section mc-practical" id="practical"><div><h2>{t('Чтобы команде<br>было удобно','Et võistkonnal<br>oleks mugav','Make the day<br>work for your team')}</h2><p>{t('Всё, что нужно ответственному за поездку: от питания до обратной дороги.','Info reisi korraldajale: toitlustusest tagasisõiduni.','Information for the trip coordinator, from food to the journey home.')}</p>{link('/visit/',t('Вся практическая информация','Kogu praktiline info','All practical information'))}</div><div>{''.join(acc(a,para(b)) for a,b in practical)}</div></section>
 <section class="mc-sauna"><img src="{base}/assets/sauna-1600.webp" alt="{t('Банная деревня у моря','Saunaküla mere ääres','Sauna village by the sea')}" loading="lazy" width="1672" height="941"><div><p class="mc-kicker">SAUNAKÜLA</p><h2>{t('После спорта —<br>в тепло','Pärast sporti<br>sooja','Warm up<br>after the sport')}</h2><p>{t('Посещение бань включено для участников команды. В вашем графике предусмотрено время для отдыха и фестивальных активностей.','Saunade külastus sisaldub võistkonna osalustasus. Ajakavas on aega puhkuseks ja festivali tegevusteks.','Sauna access is included for team participants. Your schedule allows time for rest and festival activities.')}</p>{link('/festival/warmth/',t('О банной деревне','Saunakülast','About the sauna village'))}</div></section>
 <section class="mc-section" id="rules"><div class="mc-section-head"><div><h2>{t('Правила в одном месте','Reeglid ühes kohas','Rules in one place')}</h2><p>{t('Общие условия — здесь. Правила конкретной игры — в карточке дисциплины выше.','Üldtingimused on siin. Konkreetse ala reeglid leiad ülal selle ala kaardilt.','General conditions are here. Rules for each sport are in its card above.')}</p></div><span class="mc-status">{t('Версия 1.0 · 22.09.2026','Versioon 1.0 · 22.09.2026','Version 1.0 · 22.09.2026')}</span></div><div class="mc-rules-layout"><div>{''.join(acc(a,para(b)) for a,b in rules)}</div><aside class="mc-document"><span class="mc-doc-mark" aria-hidden="true">PDF</span><h3>{t('Утверждённая версия','Kinnitatud versioon','Approved version')}</h3><p>{t('Общие условия участия доступны на сайте и в PDF. Передайте их ответственному и участникам команды.','Üldtingimused on veebis ja PDF-failina. Jagage neid kontaktisiku ja võistkonna liikmetega.','General conditions are available online and as a PDF. Share them with the coordinator and team members.')}</p>{rulesLink}</aside></div></section>
 <section class="mc-captain mc-section" id="captain"><div><h2>{t('Памятка<br>ответственному','Meelespea<br>kontaktisikule','Coordinator’s<br>checklist')}</h2><p>{t('Отмечайте готовое. Список сохраняется только в этом браузере.','Märkige tehtud sammud. Nimekiri salvestub ainult selles brauseris.','Tick off completed steps. Your checklist is saved only in this browser.')}</p><div class="mc-check-progress"><span id="mc-progress" role="status">0 / {len(checks)}</span><progress id="mc-progress-bar" value="0" max="{len(checks)}" aria-label="{t('Готовность команды','Võistkonna valmisolek','Team preparation')}"></progress></div><div class="mc-tools"><button type="button" data-mc-share data-done="{t('Ссылка скопирована','Link kopeeritud','Link copied')}" data-failed="{t('Скопируйте адрес страницы из браузера','Kopeerige aadress brauserist','Copy the address from your browser')}">{t('Скопировать ссылку','Kopeeri link','Copy link')}</button><button type="button" data-mc-print>{t('Распечатать страницу','Prindi leht','Print this page')}</button></div><p class="mc-share-status" role="status"></p></div><div class="mc-checklist">{''.join(f'<label><input type="checkbox" data-mc-check="{i}"><span>{v}</span></label>' for i,v in enumerate(checks))}</div></section>
 <section class="mc-contact"><div><h2>{t('Обсудим вашу команду','Räägime teie võistkonnast','Let’s discuss your team')}</h2><p>{t('Вопросы об участии самоуправления, составе, оплате или особых условиях — напишите нам.','Küsimused omavalitsuse osalemise, koosseisu, tasumise või eritingimuste kohta? Kirjutage meile.','Questions about municipal entry, eligibility, payment or access requirements? Get in touch.')}</p></div><a href="mailto:info@winterfest.ee">info@winterfest.ee <span aria-hidden="true">↗</span></a></section>
 </main>'''
 p=ROOT/'docs'/('' if lang=='ru' else lang)/'winter-cup/municipalities/index.html'
 s=p.read_text();s=re.sub(r'<main\b.*?</main>',lambda _:out,s,flags=re.S)
 for kind,file in [('css','municipal.css'),('js','municipal.js')]:
  if file not in s:s=s.replace('</head>',(f'<link rel="stylesheet" href="{base}/{file}">' if kind=='css' else f'<script defer src="{base}/{file}"></script>')+'</head>')
 title=t('Winter Cup для самоуправлений — 22 января 2027','Winter Cup omavalitsustele — 22. jaanuar 2027','Winter Cup for municipalities — 22 January 2027')
 s=re.sub(r'<title>.*?</title>',f'<title>{title}</title>',s)
 s=re.sub(r'(<meta property="og:title" content=")[^"]*',lambda m:m[1]+esc(title),s)
 p.write_text(s)
print('Rendered municipality pages in RU, ET and EN')
