# -*- coding: utf-8 -*-
"""Render the open-entry Cup pages in RU, ET and EN."""
from pathlib import Path
import json,re,html
ROOT=Path(__file__).resolve().parent.parent
D=json.loads((ROOT/'content/municipal-cup.json').read_text())
for idx,lang in enumerate(['ru','et','en']):
 def t(ru,et,en):return [ru,et,en][idx]
 def esc(v):return html.escape(str(v),quote=True)
 base='/narva-joesuu-winter-fest'
 pref=base+('' if lang=='ru' else '/'+lang)
 def image(name,cls=''):
  return f'<img class="{cls}" src="{base}/assets/{name}" alt="" loading="lazy" width="160" height="160">'
 def link(route,label,cls='text-link'):
  return f'<a class="{cls}" href="{pref+route}">{label}<span aria-hidden="true">↗</span></a>'
 def pending():return t('Уточняется','Täpsustamisel','To be confirmed')
 def acc(title,body,ident=''):
  return f'<details class="mc-accordion"'+(f' id="{ident}"' if ident else '')+f'><summary>{title}<span aria-hidden="true">+</span></summary><div class="mc-answer">{body}</div></details>'
 def para(s):return f'<p>{s}</p>'
 nav=[('overview',t('Главное','Ülevaade','Overview')),('team',t('Команда','Võistkond','Team')),('sports',t('Дисциплины','Alad','Sports')),('day',t('Программа дня','Päevakava','The day')),('registration',t('Стоимость и запись','Hind ja registreerimine','Fees & entry')),('practical',t('Практическое','Praktiline info','Practical info')),('rules',t('Регламенты','Juhendid','Rules'))]
 cards=''
 for sport in D['disciplines']:
  route='/winter-cup/open/disciplines/'+sport['id']+'/'
  cards+=f'<a class="mc-discipline" id="sport-{sport["id"]}" href="{pref+route}" aria-label="{esc(sport["name"][idx]+t(" — регламент"," — juhend"," — rules"))}">{image(sport["icon"])}<span>{esc(sport["name"][idx])}</span></a>'

 intro=t('Собери друзей<br>Зима зовёт','Kutsu sõbrad kaasa<br>Talv kutsub','Bring your friends<br>Winter is calling')
 nav=[('team',t('О соревнованиях','Võistlusest','About the event')),('sports',t('Дисциплины','Alad','Disciplines')),('registration',t('Как участвовать','Osalemine','How to enter')),('rules',t('Регламент','Üldjuhend','General rules'))]
 included=[('02-skis.webp',t('Испытания и инвентарь','Katsed ja varustus','Challenges & equipment')),('12-thermos.webp',t('Два приёма пищи','Kaks toidukorda','Two meals')),('13-sauna.webp',t('Посещение бань','Saunad','Sauna access')),('07-stage.webp',t('Шоу и концерт','Show ja kontsert','Show & concert')),('36-warm-tent.webp',t('Тёплые раздевалки и хранение вещей','Soojad riietusruumid ja asjade hoidmine','Heated changing rooms & storage')),('35-trophy.webp',t('Парад и награждение','Paraad ja autasustamine','Parade & awards'))]
 steps=[(t('Выберите билет команды','Valige võistkonnapilet','Choose a team ticket'),t('В регистрации укажите название команды и контакт человека, которому отправить информацию. Полный состав можно сообщить позже.','Registreerimisel märkige võistkonna nimi ja kontaktisik, kellele saata info. Täieliku koosseisu saate teatada hiljem.','Enter your team name and a contact person to receive the event information. You can provide the full roster later.')),(t('Подтвердите участие оплатой','Kinnitage osalemine maksega','Confirm your place with payment'),t('Стоимость фиксируется по дате заявки. После оплаты место за вашей командой закреплено. В цену уже включены игры, инвентарь, два приёма пищи, бани и вечерняя программа.','Hind fikseeritakse registreerimise kuupäeval. Pärast tasumist on võistkonna koht kinnitatud. Hinnas on mängud, varustus, kaks toidukorda, saunad ja õhtuprogramm.','Your fee is fixed on the application date. Payment secures your team’s place. Games, equipment, two meals, saunas and the evening programme are included.')),(t('Сообщите состав до 19 января','Saatke koosseis 19. jaanuariks','Send your roster by 19 January'),t('Отправьте имена пяти участников на info@winterfest.ee. Мы пришлём расписание вашей команды и информацию о встрече. Возьмите тёплую одежду и сменные вещи; дорогу спланируйте самостоятельно.','Saatke viie osaleja nimed aadressile info@winterfest.ee. Saadame võistkonna ajakava ja kogunemisinfo. Võtke kaasa soojad riided ja vahetusriided; transpordi korraldate ise.','Email the five participants’ names to info@winterfest.ee. We will send your team schedule and meeting details. Bring warm clothes and a change of clothing; arrange your own travel.'))]
 out=f'''<main id="main" class="municipal-page open-page">

 <section class="mc-hero" id="overview"><div class="mc-hero-copy"><h1>{intro}</h1><div class="mc-actions"><a class="button" data-open-register href="https://fienta.com/et/204081" target="_blank" rel="noopener">{t('Зарегистрироваться','Registreeru','Register')}<span aria-hidden="true">↗</span></a></div></div><div class="mc-hero-visual"><img class="mc-photo" src="{base}/assets/cup-1600.webp" srcset="{base}/assets/cup-800.webp 800w, {base}/assets/cup-1600.webp 1600w" sizes="(max-width:760px) 100vw,55vw" width="1672" height="941" alt="{t('Командная игра на зимнем берегу','Võistkonnamäng talvisel rannal','Team sport on the winter coast')}" fetchpriority="high"><div class="mc-date"><strong>22.01</strong><span>{t('ПЯТНИЦА','REEDE','FRIDAY')} · 2027</span></div>{image('23-team.webp','mc-hero-object')}</div></section>
 <div class="mc-facts"><div><span>{t('Место','Asukoht','Location')}</span><strong>Narva-Jõesuu</strong></div><div><span>{t('Участники','Osalejad','Participants')}</span><strong>{t('Все желающие · 16+','Kõik huvilised · 16+','Everyone aged 16+')}</strong></div><div><span>{t('Команда','Võistkond','Team')}</span><strong>{t('5 участников','5 osalejat','5 participants')}</strong></div><div><span>{t('Программа дня','Päevakava','Day programme')}</span><strong>~11:00–19:00</strong></div></div>
 <nav class="mc-jump" aria-label="{t('Разделы страницы','Lehe jaotised','Page sections')}"><span class="mc-jump-label">{t('На этой странице','Sellel lehel','On this page')}</span><div>{''.join(f'<a href="#{a}">{b}</a>' for a,b in nav)}</div></nav>
 <section class="mc-section mc-story" id="team"><div class="mc-story-intro"><h2>{t('Один день<br>Будет что вспомнить','Üks päev<br>Palju, mida meenutada','One day<br>Plenty to remember')}</h2><div><p class="mc-story-lead">{t('Winter Cup — командные игры на зимнем берегу Нарва-Йыэсуу. Соберите пятерых друзей, родных или знакомых и приезжайте на день, в котором есть место соревнованиям, баням и концерту.','Winter Cup on võistkonnamängud talvisel Narva-Jõesuu rannal. Pange kokku viieliikmeline sõprade, pereliikmete või tuttavate võistkond ja tulge päevale, kuhu mahuvad võistlused, saunad ja kontsert.','Winter Cup brings team games to the winter coast of Narva-Jõesuu. Get five friends, relatives or acquaintances together for a day of challenges, saunas and live music.')}</p><p>{t('Спортивный опыт не нужен. Где-то пригодится меткость, где-то скорость, а где-то умение договориться и поддержать друг друга. Можно всерьёз побороться за первое место, а можно просто попробовать всё вместе.','Spordikogemus ei ole vajalik. Mõnes mängus loeb täpsus, teises kiirus, kolmandas koostöö ja üksteise toetamine. Võite püüda esikohta või lihtsalt kõike koos proovida.','No sporting experience needed. Some games call for accuracy, others for speed, teamwork or a little encouragement. Aim for first place or enjoy trying everything together.')}</p></div></div>
 <div class="mc-story-format"><div class="mc-story-symbol">{image('23-team.webp')}<span>{t('Вся команда вместе','Kogu võistkond koos','The whole team together')}</span></div><div><h3>{t('От испытаний до вечернего концерта','Katsetest õhtuse kontserdini','From challenges to the evening concert')}</h3><p>{t('Встречаемся утром, знакомимся с заданиями и отправляемся по игровым станциям. Вы всё время вместе: каждое испытание приносит баллы в общий результат. Между играми есть время поесть и отдохнуть. После — бани, награждение и концерт для участников. Для победителей предусмотрены небольшие призы.','Koguneme hommikul, tutvume ülesannetega ja liigume mängupunktidesse. Läbite need koos ning iga ala punktid lähevad üldarvestusse. Mängude vahel on söögi- ja puhkepausid. Seejärel ootavad saunad, autasustamine ja osalejate kontsert. Võitjatele on väikesed auhinnad.','Meet in the morning, hear the briefing and head to the game stations. You stay together, collecting points towards your team result. There is time to eat and rest between games, then enjoy the saunas, awards and participants’ concert. There will be small prizes for the winners.')}</p></div></div>
 <div class="mc-package"><h3>{t('Всё это входит в стоимость команды','Kõik see sisaldub võistkonna hinnas','All included in the team fee')}</h3><div class="mc-package-grid">{''.join(f'<div>{image(icon)}<span>{label}</span></div>' for icon,label in included)}</div></div>
 <div class="mc-eligibility"><h3>{t('С кем приехать','Kellega tulla','Who to bring')}</h3><p>{t('С друзьями, семьёй, соседями или знакомыми. В команде пять человек от 16 лет. Не нужно работать или учиться вместе, жить в одном городе или состоять в спортивном клубе.','Sõprade, pere, naabrite või tuttavatega. Võistkonnas on viis vähemalt 16-aastast osalejat. Te ei pea koos töötama ega õppima, samas linnas elama või spordiklubisse kuuluma.','Friends, family, neighbours or acquaintances: five people aged 16 or over. You do not need to work or study together, live in the same town or belong to a sports club.')}</p></div></section>
 <section class="mc-section mc-sports-section" id="sports"><div class="mc-section-head"><div><h2>{t('Дисциплины','Alad','Disciplines')}</h2></div></div><div class="mc-sport-grid">{cards}</div></section>
 <section class="mc-section mc-entry" id="registration"><h2>{t('Как принять участие?','Kuidas osaleda?','How to take part?')}</h2><div class="mc-entry-grid"><div class="mc-fees"><p class="mc-fees-label">{t('Стоимость за команду из 5 человек','Hind viieliikmelisele võistkonnale','Fee for a team of 5')}</p><div class="mc-tier"><span>{t('До 31 декабря','Kuni 31. detsembrini','Until 31 December')}</span><strong>90 €<small>{t("18 € с человека","18 € inimese kohta","€18 per person")}</small></strong></div><div class="mc-tier"><span>{t('1–10 января','1.–10. jaanuar','1–10 January')}</span><strong>120 €<small>{t("24 € с человека","24 € inimese kohta","€24 per person")}</small></strong></div><div class="mc-tier"><span>{t('11–17 января','11.–17. jaanuar','11–17 January')}</span><strong>150 €<small>{t("30 € с человека","30 € inimese kohta","€30 per person")}</small></strong></div><a class="button button-light" data-open-register href="https://fienta.com/et/204081" target="_blank" rel="noopener">{t('Зарегистрировать команду','Registreeri võistkond','Register your team')}<span aria-hidden="true">↗</span></a><p class="mc-entry-deadline">{t('Регистрация до 17 января','Registreerimine 17. jaanuarini','Registration closes 17 January')}</p></div><div class="mc-admin"><h3>{t('Договоритесь с друзьями — остальное просто','Leppige sõpradega kokku','Get your friends together')}</h3>{''.join(f'<article><h4>{title}</h4><p>{body}</p></article>' for title,body in steps)}</div></div></section>
 <aside class="oc-solo"><h3>{t('Не набирается пятёрка?','Viis inimest ei tule kokku?','Short of a full team?')}</h3><p>{t('Можно записаться одному: вы оплачиваете одно место, а мы собираем команду из участников, которые тоже пришли без своей пятёрки. Тариф за человека тот же — 18, 24 или 30 € в зависимости от даты регистрации.','Saate registreeruda ka üksi: tasute ühe koha eest ja meie paneme kokku võistkonna teistest üksikosalejatest. Hind inimese kohta on sama — 18, 24 või 30 € vastavalt registreerimise kuupäevale.','You can also enter on your own. Pay for one place and we will put you in a team with other individual entrants. The same per-person rates apply: €18, €24 or €30, depending on when you register.')}</p><a class="text-link" data-open-solo href="mailto:info@winterfest.ee?subject=Winter%20Cup%20individual">{t('Написать об участии одному','Kirjuta üksikosalemise kohta','Ask about individual entry')}<span aria-hidden="true">↗</span></a></aside>
 <section class="mc-section mc-rules-compact" id="rules"><div><h2>{t('Общий регламент','Üldjuhend','General rules')}</h2><p>{t('Регламент открытой категории появится здесь позднее. Его можно будет прочитать на сайте и скачать в PDF.','Avatud kategooria juhend ilmub siia hiljem. Seda saab lugeda veebis ja alla laadida PDF-failina.','The open category rules will be published here later, to read online or download as a PDF.')}</p></div></section>
 <div class="mc-programme-link">{link('/programme/',t('Смотреть программу','Vaata programmi','View programme'),'button')}</div>
 <section class="mc-contact"><div><h2>{t('Остались вопросы?','Kas on küsimusi?','Any questions?')}</h2><p>{t('Напишите нам, если нужна помощь с регистрацией или хочется уточнить условия участия.','Kirjutage meile, kui vajate registreerimisel abi või soovite osalemise kohta midagi täpsustada.','Get in touch if you need help registering or have questions about taking part.')}</p></div><a href="mailto:info@winterfest.ee">info@winterfest.ee <span aria-hidden="true">↗</span></a></section>
 </main>'''
 p=ROOT/'docs'/('' if lang=='ru' else lang)/'winter-cup/open/index.html'
 s=p.read_text();s=re.sub(r'<main\b.*?</main>',lambda _:out,s,flags=re.S)
 for kind,file in [('css','municipal.css'),('js','municipal.js')]:
  if file not in s:s=s.replace('</head>',(f'<link rel="stylesheet" href="{base}/{file}">' if kind=='css' else f'<script defer src="{base}/{file}"></script>')+'</head>')
 title=t('Winter Cup для всех желающих — 22 января 2027','Winter Cup kõigile huvilistele — 22. jaanuar 2027','Winter Cup for everyone — 22 January 2027')
 s=re.sub(r'<title>.*?</title>',f'<title>{title}</title>',s)
 s=re.sub(r'(<meta property="og:title" content=")[^"]*',lambda m:m[1]+esc(title),s)
 p.write_text(s)
print('Rendered open pages in RU, ET and EN')
