# -*- coding: utf-8 -*-
"""Render only the municipality pages. Keep the site's shared header/footer intact."""
from pathlib import Path
import json,re,html
ROOT=Path(__file__).resolve().parent.parent
D=json.loads((ROOT/'content/municipal-cup.json').read_text())
for idx,lang in enumerate(['ru','et','en']):
 def t(ru,et,en):return [ru,et,en][idx]
 def esc(v):return html.escape(str(v),quote=True)
 base='/narva-joesuu-winter-fest'
 pref=base+('' if lang=='ru' else '/'+lang)
 def image(name,cls=''):
  return f'<img class="{cls}" src="{base}/assets/{name}" alt="" loading="lazy" width="160" height="160">'
 def link(route,label,cls='text-link'):
  return f'<a class="{cls}" href="{pref+route}">{label}<span aria-hidden="true">↗</span></a>'
 def pending():return t('Уточняется','Täpsustamisel','To be confirmed')
 def acc(title,body,ident=''):
  return f'<details class="mc-accordion"'+(f' id="{ident}"' if ident else '')+f'><summary>{title}<span aria-hidden="true">+</span></summary><div class="mc-answer">{body}</div></details>'
 def para(s):return f'<p>{s}</p>'
 nav=[('overview',t('Главное','Ülevaade','Overview')),('team',t('Команда','Võistkond','Team')),('sports',t('Дисциплины','Alad','Sports')),('day',t('Программа дня','Päevakava','The day')),('registration',t('Стоимость и запись','Hind ja registreerimine','Fees & entry')),('practical',t('Практическое','Praktiline info','Practical info')),('rules',t('Регламенты','Juhendid','Rules'))]
 cards=''
 for sport in D['disciplines']:
  route='/winter-cup/municipalities/disciplines/'+sport['id']+'/'
  cards+=f'<a class="mc-discipline" id="sport-{sport["id"]}" href="{pref+route}" aria-label="{esc(sport["name"][idx]+t(" — регламент"," — juhend"," — rules"))}">{image(sport["icon"])}<span>{esc(sport["name"][idx])}</span></a>'

 intro=t('Представьте свой<br>город или волость','Esinda oma<br>linna või valda','Represent your<br>city or municipality')
 nav=[('team',t('О соревнованиях','Võistlusest','About the event')),('sports',t('Дисциплины','Alad','Disciplines')),('registration',t('Как участвовать','Osalemine','How to enter')),('rules',t('Регламент','Üldjuhend','General rules'))]
 included=[('02-skis.webp',t('Испытания и инвентарь','Katsed ja varustus','Challenges & equipment')),('12-thermos.webp',t('Два приёма пищи','Kaks toidukorda','Two meals')),('13-sauna.webp',t('Посещение бань','Saunad','Sauna access')),('07-stage.webp',t('Шоу и концерт','Show ja kontsert','Show & concert')),('36-warm-tent.webp',t('Тёплые раздевалки и хранение вещей','Soojad riietusruumid ja asjade hoidmine','Heated changing rooms & storage')),('35-trophy.webp',t('Парад и награждение','Paraad ja autasustamine','Parade & awards'))]
 steps=[(t('Подайте заявку от самоуправления','Esitage omavalitsuse taotlus','Apply on behalf of your municipality'),t('В Fienta укажите самоуправление, название команды, контакт ответственного и реквизиты для счёта. Имена всех участников пока не нужны.','Märkige Fientas omavalitsus, võistkonna nimi, kontaktisik ja arveandmed. Kõigi osalejate nimesid veel vaja ei ole.','Enter the municipality, team name, coordinator’s contact and billing details in Fienta. The full roster is not needed yet.')),(t('Оплатите счёт','Tasuge arve','Pay the invoice'),t('После заявки организатор выставит счёт на указанные реквизиты. Место команды подтверждается после оплаты. Тариф фиксируется в день заявки.','Pärast taotluse esitamist väljastab korraldaja arve märgitud andmetele. Koht kinnitatakse pärast tasumist. Hind fikseeritakse taotluse esitamise päeval.','The organiser will issue an invoice using the details provided. Payment confirms your team’s place. The fee is fixed on the application date.')),(t('Передайте состав до 19 января','Saatke koosseis 19. jaanuariks','Send the roster by 19 January'),t('Отправьте имена и места работы пяти участников на info@winterfest.ee. Ответственный получит график команды и информацию для поездки.','Saatke viie osaleja nimed ja töökohad aadressile info@winterfest.ee. Kontaktisik saab võistkonna ajakava ja saabumisinfo.','Email the five participants’ names and workplaces to info@winterfest.ee. The coordinator will receive the team’s schedule and arrival information.'))]
 out=f'''<main id="main" class="municipal-page">

 <section class="mc-hero" id="overview"><div class="mc-hero-copy"><h1>{intro}</h1><div class="mc-actions"><a class="button" data-registration="municipalities" href="https://fienta.com/et/204033">{t('Зарегистрироваться','Registreeru','Register')}<span aria-hidden="true">↗</span></a></div></div><div class="mc-hero-visual"><img class="mc-photo" src="{base}/assets/cup-1600.webp" srcset="{base}/assets/cup-800.webp 800w, {base}/assets/cup-1600.webp 1600w" sizes="(max-width:760px) 100vw,55vw" width="1672" height="941" alt="{t('Командная игра на зимнем берегу','Võistkonnamäng talvisel rannal','Team sport on the winter coast')}" fetchpriority="high"><div class="mc-date"><strong>22.01</strong><span>{t('ПЯТНИЦА','REEDE','FRIDAY')} · 2027</span></div>{image('cup-municipality-ribbon.png','mc-hero-object')}</div></section>
 <div class="mc-facts"><div><span>{t('Место','Asukoht','Location')}</span><strong>Narva-Jõesuu</strong></div><div><span>{t('Участники','Osalejad','Participants')}</span><strong>{t('Города и волости','Linnad ja vallad','Cities and municipalities')}</strong></div><div><span>{t('Команда','Võistkond','Team')}</span><strong>{t('5 участников · 16+','5 osalejat · 16+','5 participants · 16+')}</strong></div><div><span>{t('Программа дня','Päevakava','Day programme')}</span><strong>~11:00–19:00</strong></div></div>
 <nav class="mc-jump" aria-label="{t('Разделы страницы','Lehe jaotised','Page sections')}"><span class="mc-jump-label">{t('На этой странице','Sellel lehel','On this page')}</span><div>{''.join(f'<a href="#{a}">{b}</a>' for a,b in nav)}</div></nav>
 <section class="mc-section mc-story" id="team"><div class="mc-story-intro"><h2>{t('Один день<br>Одной командой','Üks päev<br>Ühe võistkonnana','One day<br>One team')}</h2><div><p class="mc-story-lead">{t('Winter Cup — соревнования между командами городских и волостных самоуправлений. Пять коллег представляют свой город или волость в зимних спортивных и командных испытаниях.','Winter Cup on linnade ja valdade võistkondade vaheline võistlus. Viis kolleegi esindavad oma omavalitsust talvistes spordi- ja meeskonnakatsetes.','Winter Cup brings city and rural municipal teams together in competition. Five colleagues represent their municipality in winter sports and team challenges.')}</p><p>{t('Вместо привычных рабочих задач — общий маршрут, новые роли и поддержка друг друга. Здесь можно познакомиться с коллегами из других учреждений и самоуправлений, выйти на парад под своим флагом и вместе побороться за место на пьедестале.','Igapäevatöö asemel ootavad ühine rada, uued rollid ja üksteise toetamine. Saate tuttavaks teiste asutuste ja omavalitsuste kolleegidega, osalete oma lipu all paraadil ning võistlete koos poodiumikoha nimel.','Swap the working day for a shared route, new roles and supporting each other. Meet colleagues from other institutions and municipalities, join the parade under your flag and compete together for a place on the podium.')}</p></div></div>
 <div class="mc-story-format"><div class="mc-story-symbol">{image('23-team.webp')}<span>{t('Вся команда вместе','Kogu võistkond koos','The whole team together')}</span></div><div><h3>{t('От испытаний до вечернего концерта','Katsetest õhtuse kontserdini','From challenges to the evening concert')}</h3><p>{t('После встречи и инструктажа команда проходит пункты по своему графику. На каждом испытании вы набираете баллы в общий зачёт. В маршруте предусмотрены перерывы на питание и отдых, а после спортивной части — бани, шоу, награждение трёх лучших команд и концерт для участников.','Pärast kogunemist ja juhendamist läbib võistkond punktid oma ajakava järgi. Igal alal kogute punkte üldarvestusse. Kavas on söögi- ja puhkepausid ning pärast sporti saunad, show, kolme parima võistkonna autasustamine ja osalejate kontsert.','After check-in and briefing, your team follows its own schedule between stations, earning points towards the overall result. There are meal and rest breaks, followed by saunas, a show, awards for the top three teams and a participants’ concert.')}</p></div></div>
 <div class="mc-package"><h3>{t('Всё это входит в стоимость команды','Kõik see sisaldub võistkonna hinnas','All included in the team fee')}</h3><div class="mc-package-grid">{''.join(f'<div>{image(icon)}<span>{label}</span></div>' for icon,label in included)}</div></div>
 <div class="mc-eligibility"><h3>{t('Кого пригласить в команду','Keda võistkonda kutsuda','Who can join your team')}</h3><p>{t('Работников управы, подчинённых ей учреждений и принадлежащих самоуправлению предприятий, а также членов городского или волостного собрания. Пять участников от 16 лет; спортивная подготовка может быть любой. Самоуправление может заявить несколько команд.','Linna- või vallavalitsuse, selle hallatavate asutuste ja omavalitsusele kuuluvate ettevõtete töötajaid ning volikogu liikmeid. Võistkonnas on viis vähemalt 16-aastast osalejat; sportlik tase ei ole piiratud. Üks omavalitsus võib registreerida mitu võistkonda.','Municipal government staff, employees of its subordinate institutions and municipally owned enterprises, and council members. Each team has five participants aged 16+, with no sporting-level requirement. A municipality may enter several teams.')}</p></div></section>
 <section class="mc-section mc-sports-section" id="sports"><div class="mc-section-head"><div><h2>{t('Дисциплины','Alad','Disciplines')}</h2></div></div><div class="mc-sport-grid">{cards}</div></section>
 <section class="mc-section mc-entry" id="registration"><h2>{t('Как принять участие?','Kuidas osaleda?','How to take part?')}</h2><div class="mc-entry-grid"><div class="mc-fees"><p class="mc-fees-label">{t('Стоимость за команду из 5 человек','Hind viieliikmelisele võistkonnale','Fee for a team of 5')}</p><div class="mc-tier"><span>{t('До 31 декабря','Kuni 31. detsembrini','Until 31 December')}</span><strong>90 €</strong></div><div class="mc-tier"><span>{t('1–10 января','1.–10. jaanuar','1–10 January')}</span><strong>120 €</strong></div><div class="mc-tier"><span>{t('11–17 января','11.–17. jaanuar','11–17 January')}</span><strong>150 €</strong></div><a class="button button-light" data-registration="municipalities" href="https://fienta.com/et/204033">{t('Зарегистрироваться','Registreeru','Register')}<span aria-hidden="true">↗</span></a><p class="mc-entry-deadline">{t('Регистрация до 17 января','Registreerimine 17. jaanuarini','Registration closes 17 January')}</p></div><div class="mc-admin"><h3>{t('Для ответственного за участие','Osalemise korraldajale','For the municipal coordinator')}</h3>{''.join(f'<article><h4>{title}</h4><p>{body}</p></article>' for title,body in steps)}</div></div></section>
 <section class="mc-section mc-rules-compact" id="rules"><div><h2>{t('Общий регламент','Üldjuhend','General rules')}</h2><p>{t('Условия допуска, замены участников, подсчёт результатов и возвраты — в одном документе.','Osalemistingimused, liikmete asendamine, punktiarvestus ja tagastused ühes dokumendis.','Eligibility, roster changes, scoring and refunds in one document.')}</p></div><div class="mc-rule-links">{link('/winter-cup/municipalities/rules/',t('Читать регламент','Loe juhendit','Read the rules'),'button')}<a class="mc-inline" href="{D['rulesPdf'][lang]}" target="_blank" rel="noopener">{t('Скачать PDF','Laadi alla PDF','Download PDF')}</a></div></section>
 <div class="mc-programme-link">{link('/programme/',t('Смотреть программу','Vaata programmi','View programme'),'button')}</div>
 <section class="mc-contact"><div><h2>{t('Обсудим вашу команду','Räägime teie võistkonnast','Let’s discuss your team')}</h2><p>{t('Вопросы об участии самоуправления, составе, оплате или особых условиях — напишите нам.','Küsimused omavalitsuse osalemise, koosseisu, tasumise või eritingimuste kohta? Kirjutage meile.','Questions about municipal entry, eligibility, payment or access requirements? Get in touch.')}</p></div><a href="mailto:info@winterfest.ee">info@winterfest.ee <span aria-hidden="true">↗</span></a></section>
 </main>'''
 p=ROOT/'docs'/('' if lang=='ru' else lang)/'winter-cup/municipalities/index.html'
 s=p.read_text();s=re.sub(r'<main\b.*?</main>',lambda _:out,s,flags=re.S)
 for kind,file in [('css','municipal.css'),('js','municipal.js')]:
  if file not in s:s=s.replace('</head>',(f'<link rel="stylesheet" href="{base}/{file}">' if kind=='css' else f'<script defer src="{base}/{file}"></script>')+'</head>')
 title=t('Winter Cup для самоуправлений — 22 января 2027','Winter Cup omavalitsustele — 22. jaanuar 2027','Winter Cup for municipalities — 22 January 2027')
 s=re.sub(r'<title>.*?</title>',f'<title>{title}</title>',s)
 s=re.sub(r'(<meta property="og:title" content=")[^"]*',lambda m:m[1]+esc(title),s)
 p.write_text(s)
print('Rendered municipality pages in RU, ET and EN')
