# -*- coding: utf-8 -*-
"""Render the company and organisation pages. Keep the site's shared header/footer intact."""
from pathlib import Path
import json,re,html
ROOT=Path(__file__).resolve().parent.parent
D=json.loads((ROOT/'content/municipal-cup.json').read_text())
for idx,lang in enumerate(['ru','et','en']):
 def t(ru,et,en):return [ru,et,en][idx]
 def esc(v):return html.escape(str(v),quote=True)
 base='/narva-joesuu-winter-fest'
 pref=base+('' if lang=='ru' else '/'+lang)
 def image(name,cls=''):
  return f'<img class="{cls}" src="{base}/assets/{name}" alt="" loading="lazy" width="160" height="160">'
 def link(route,label,cls='text-link'):
  return f'<a class="{cls}" href="{pref+route}">{label}<span aria-hidden="true">↗</span></a>'
 def pending():return t('Уточняется','Täpsustamisel','To be confirmed')
 def acc(title,body,ident=''):
  return f'<details class="mc-accordion"'+(f' id="{ident}"' if ident else '')+f'><summary>{title}<span aria-hidden="true">+</span></summary><div class="mc-answer">{body}</div></details>'
 def para(s):return f'<p>{s}</p>'
 nav=[('overview',t('Главное','Ülevaade','Overview')),('team',t('Команда','Võistkond','Team')),('sports',t('Дисциплины','Alad','Sports')),('day',t('Программа дня','Päevakava','The day')),('registration',t('Стоимость и запись','Hind ja registreerimine','Fees & entry')),('practical',t('Практическое','Praktiline info','Practical info')),('rules',t('Регламенты','Juhendid','Rules'))]
 cards=''
 for sport in D['disciplines']:
  route='/winter-cup/business/disciplines/'+sport['id']+'/'
  cards+=f'<a class="mc-discipline" id="sport-{sport["id"]}" href="{pref+route}" aria-label="{esc(sport["name"][idx]+t(" — регламент"," — juhend"," — rules"))}">{image(sport["icon"])}<span>{esc(sport["name"][idx])}</span></a>'

 intro=t('Коллеги в деле<br>Команда на старте','Kolleegid koos<br>Võistkond stardis','Colleagues together<br>A team at the start')
 nav=[('team',t('О соревнованиях','Võistlusest','About the event')),('sports',t('Дисциплины','Alad','Disciplines')),('registration',t('Как участвовать','Osalemine','How to enter')),('rules',t('Регламент','Üldjuhend','General rules'))]
 included=[('02-skis.webp',t('Испытания и инвентарь','Katsed ja varustus','Challenges & equipment')),('12-thermos.webp',t('Два приёма пищи','Kaks toidukorda','Two meals')),('13-sauna.webp',t('Посещение бань','Saunad','Sauna access')),('07-stage.webp',t('Шоу и концерт','Show ja kontsert','Show & concert')),('36-warm-tent.webp',t('Тёплые раздевалки и хранение вещей','Soojad riietusruumid ja asjade hoidmine','Heated changing rooms & storage')),('35-trophy.webp',t('Парад и награждение','Paraad ja autasustamine','Parade & awards'))]
 steps=[(t('Зарегистрируйте организацию','Registreerige organisatsioon','Register your organisation'),t('В Fienta укажите организацию, название команды, контакт ответственного и реквизиты для счёта. Имена всех участников на этом этапе не нужны.','Märkige Fientas organisatsioon, võistkonna nimi, kontaktisik ja arveandmed. Kõigi osalejate nimesid selles etapis vaja ei ole.','Enter your organisation, team name, coordinator’s contact and billing details in Fienta. You do not need the full roster at this stage.')),(t('Оплатите счёт','Tasuge arve','Pay the invoice'),t('После заявки организатор выставит счёт на указанные реквизиты. Место команды подтверждается после оплаты. Тариф фиксируется в день заявки.','Pärast taotluse esitamist väljastab korraldaja arve märgitud andmetele. Koht kinnitatakse pärast tasumist. Hind fikseeritakse taotluse esitamise päeval.','The organiser will issue an invoice using the details provided. Payment confirms your team’s place. The fee is fixed on the application date.')),(t('Передайте состав до 19 января','Saatke koosseis 19. jaanuariks','Send the roster by 19 January'),t('Отправьте имена и места работы пяти участников на info@winterfest.ee. Ответственный получит график команды и информацию для поездки.','Saatke viie osaleja nimed ja töökohad aadressile info@winterfest.ee. Kontaktisik saab võistkonna ajakava ja saabumisinfo.','Email the five participants’ names and workplaces to info@winterfest.ee. The coordinator will receive the team’s schedule and arrival information.'))]
 out=f'''<main id="main" class="municipal-page">

 <section class="mc-hero" id="overview"><div class="mc-hero-copy"><h1>{intro}</h1><div class="mc-actions"><a class="button" data-registration="business" href="https://fienta.com/et/204033">{t('Зарегистрироваться','Registreeru','Register')}<span aria-hidden="true">↗</span></a></div></div><div class="mc-hero-visual"><img class="mc-photo" src="{base}/assets/cup-1600.webp" srcset="{base}/assets/cup-800.webp 800w, {base}/assets/cup-1600.webp 1600w" sizes="(max-width:760px) 100vw,55vw" width="1672" height="941" alt="{t('Командная игра на зимнем берегу','Võistkonnamäng talvisel rannal','Team sport on the winter coast')}" fetchpriority="high"><div class="mc-date"><strong>22.01</strong><span>{t('ПЯТНИЦА','REEDE','FRIDAY')} · 2027</span></div>{image('cup-business-ribbon.png','mc-hero-object')}</div></section>
 <div class="mc-facts"><div><span>{t('Место','Asukoht','Location')}</span><strong>Narva-Jõesuu</strong></div><div><span>{t('Участники','Osalejad','Participants')}</span><strong>{t('Компании и организации','Ettevõtted ja organisatsioonid','Companies & organisations')}</strong></div><div><span>{t('Команда','Võistkond','Team')}</span><strong>{t('5 участников · 16+','5 osalejat · 16+','5 participants · 16+')}</strong></div><div><span>{t('Программа дня','Päevakava','Day programme')}</span><strong>~11:00–19:00</strong></div></div>
 <nav class="mc-jump" aria-label="{t('Разделы страницы','Lehe jaotised','Page sections')}"><span class="mc-jump-label">{t('На этой странице','Sellel lehel','On this page')}</span><div>{''.join(f'<a href="#{a}">{b}</a>' for a,b in nav)}</div></nav>
 <section class="mc-section mc-story" id="team"><div class="mc-story-intro"><h2>{t('Ваш коллектив<br>За пределами работы','Teie kollektiiv<br>Väljaspool tööd','Your team<br>Beyond the workplace')}</h2><div><p class="mc-story-lead">{t('Winter Cup — зимний командный день для компаний, организаций и учреждений. Соберите пять коллег: из офиса, производства, гимназии или любого другого коллектива. Вас ждут соревнования у моря и общая вечерняя программа.','Winter Cup on talvine meeskonnapäev ettevõtetele, organisatsioonidele ja asutustele. Kutsuge kokku viis kolleegi kontorist, tootmisest, gümnaasiumist või mujalt. Teid ootavad võistlused mere ääres ja ühine õhtuprogramm.','Winter Cup is a winter team day for companies, organisations and institutions. Bring five colleagues from your office, workshop, upper secondary school or other workplace for seaside challenges and an evening programme together.')}</p><p>{t('На работе у каждого свои задачи. Здесь вы проходите испытания вместе, помогаете друг другу и знакомитесь с коллегами с другой стороны. Спортивный выезд и небольшой корпоратив уже собраны в один день — от первого старта до концерта. Приезжать можно из любого региона.','Tööl on igaühel oma ülesanded. Siin läbite katsed koos, toetate üksteist ja näete kolleege uues rollis. Sportlik väljasõit ja ühine pidu mahuvad ühte päeva, esimesest stardist kontserdini. Oodatud on kollektiivid kõigist piirkondadest.','At work, everyone has their own responsibilities. Here you tackle challenges together, support each other and discover a different side of your colleagues. The sporting outing and team celebration are already planned, from the first start to the concert. Teams from every region are welcome.')}</p></div></div>
 <div class="bc-presence"><div>{image('cup-business-ribbon.png')}</div><div><h3>{t('Представьте тех, с кем работаете','Esindage oma kollektiivi','Put your team’s name out there')}</h3><p>{t('Возьмите флаг, фирменные шарфы или другую символику. На параде, во время игр и на награждении вы выступаете под именем своей организации. Это повод познакомиться с другими коллективами и дать коллегам и гостям фестиваля команду, за которую можно болеть.','Võtke kaasa lipp, logoga sallid või muu sümboolika. Paraadil, mängudel ja autasustamisel esindate oma organisatsiooni. Saate tutvuda teiste kollektiividega ning anda kolleegidele ja festivali külalistele oma võistkonna, kellele kaasa elada.','Bring your flag, branded scarves or other team colours. In the parade, during the games and at the awards, you represent your organisation. Meet other workplaces and give colleagues and festival visitors a team to cheer for.')}</p></div></div>
 <div class="mc-story-format"><div class="mc-story-symbol">{image('23-team.webp')}<span>{t('Вся команда вместе','Kogu võistkond koos','The whole team together')}</span></div><div><h3>{t('От испытаний до вечернего концерта','Katsetest õhtuse kontserdini','From challenges to the evening concert')}</h3><p>{t('После встречи и инструктажа команда проходит пункты по своему графику. На каждом испытании вы набираете баллы в общий зачёт. В маршруте предусмотрены перерывы на питание и отдых, а после спортивной части — бани, шоу, награждение трёх лучших команд и концерт для участников.','Pärast kogunemist ja juhendamist läbib võistkond punktid oma ajakava järgi. Igal alal kogute punkte üldarvestusse. Kavas on söögi- ja puhkepausid ning pärast sporti saunad, show, kolme parima võistkonna autasustamine ja osalejate kontsert.','After check-in and briefing, your team follows its own schedule between stations, earning points towards the overall result. There are meal and rest breaks, followed by saunas, a show, awards for the top three teams and a participants’ concert.')}</p></div></div>
 <div class="mc-package"><h3>{t('Всё это входит в стоимость команды','Kõik see sisaldub võistkonna hinnas','All included in the team fee')}</h3><div class="mc-package-grid">{''.join(f'<div>{image(icon)}<span>{label}</span></div>' for icon,label in included)}</div></div>
 <div class="mc-eligibility"><h3>{t('Кого пригласить в команду','Keda võistkonda kutsuda','Who can join your team')}</h3><p>{t('Сотрудники по трудовому договору или договору подряда, члены правления и бывшие сотрудники в течение года после ухода. В команде может быть один родственник сотрудника, не выступавший в соответствующем или близком виде спорта в соревновательных лигах (кроме любительских) в текущем и двух предыдущих календарных годах. Один участник представляет одну команду.','Osaleda saavad töö- või töövõtulepinguga töötajad, juhatuse liikmed ja kuni aasta tagasi lahkunud töötajad. Võistkonnas võib olla üks töötaja pereliige, kes pole käesoleval ega kahel eelmisel kalendriaastal võistelnud vastaval või lähedasel alal liigades, välja arvatud rahvaliigad. Üks osaleja esindab üht võistkonda.','Employees, contractors, board members and staff who left within the past year may enter. A team may include one employee’s family member who has not competed in leagues, except recreational leagues, in the relevant or closely related sport during the current and previous two calendar years. Each person represents one team.')}</p><p class="bc-team-note">{t('Пять участников от 16 лет. Для сотрудников ограничений по спортивной подготовке нет. Компания, гимназия, учреждение или другая организация может заявить несколько команд; каждая выступает отдельно.','Viis vähemalt 16-aastast osalejat. Töötajate sportlik tase ei ole piiratud. Ettevõte, gümnaasium, asutus või muu organisatsioon võib registreerida mitu eraldi võistlevat võistkonda.','Five participants aged 16+. Employees may have any sporting background. Companies, upper secondary schools, institutions and other organisations may enter several independently competing teams.')}</p></div></section>
 <section class="mc-section mc-sports-section" id="sports"><div class="mc-section-head"><div><h2>{t('Дисциплины','Alad','Disciplines')}</h2></div></div><div class="mc-sport-grid">{cards}</div></section>
 <section class="mc-section mc-entry" id="registration"><h2>{t('Как принять участие?','Kuidas osaleda?','How to take part?')}</h2><div class="mc-entry-grid"><div class="mc-fees"><p class="mc-fees-label">{t('Стоимость за команду из 5 человек','Hind viieliikmelisele võistkonnale','Fee for a team of 5')}</p><div class="mc-tier"><span>{t('До 31 декабря','Kuni 31. detsembrini','Until 31 December')}</span><strong>90 €</strong></div><div class="mc-tier"><span>{t('1–10 января','1.–10. jaanuar','1–10 January')}</span><strong>120 €</strong></div><div class="mc-tier"><span>{t('11–17 января','11.–17. jaanuar','11–17 January')}</span><strong>150 €</strong></div><a class="button button-light" data-registration="business" href="https://fienta.com/et/204033">{t('Зарегистрироваться','Registreeru','Register')}<span aria-hidden="true">↗</span></a><p class="mc-entry-deadline">{t('Регистрация до 17 января','Registreerimine 17. jaanuarini','Registration closes 17 January')}</p></div><div class="mc-admin"><h3>{t('Для организатора выезда','Väljasõidu korraldajale','For the team coordinator')}</h3>{''.join(f'<article><h4>{title}</h4><p>{body}</p></article>' for title,body in steps)}</div></div></section>
 <section class="mc-section mc-rules-compact" id="rules"><div><h2>{t('Общий регламент','Üldjuhend','General rules')}</h2><p>{t('Регламент категории для компаний и организаций появится позднее. Здесь можно будет прочитать его и скачать PDF.','Ettevõtete ja organisatsioonide kategooria juhend avaldatakse hiljem. Siin saab seda lugeda ja PDF-failina alla laadida.','The rules for companies and organisations will be published here later, with a downloadable PDF.')}</p></div></section>
 <section class="mc-contact"><div><h2>{t('Обсудим вашу команду','Räägime teie võistkonnast','Let’s discuss your team')}</h2><p>{t('Поможем подготовить выезд вашей компании, гимназии или организации. По вопросам состава, оплаты и особых условий — напишите нам.','Aitame ette valmistada teie ettevõtte, gümnaasiumi või organisatsiooni väljasõidu. Küsimused koosseisu, tasumise või eritingimuste kohta? Kirjutage meile.','We can help your company, upper secondary school or organisation prepare its outing. Get in touch about team eligibility, payment or access requirements.')}</p></div><a href="mailto:info@winterfest.ee">info@winterfest.ee <span aria-hidden="true">↗</span></a></section>
 </main>'''
 p=ROOT/'docs'/('' if lang=='ru' else lang)/'winter-cup/business/index.html'
 s=p.read_text();s=re.sub(r'<main\b.*?</main>',lambda _:out,s,flags=re.S)
 for kind,file in [('css','municipal.css'),('js','municipal.js')]:
  if file not in s:s=s.replace('</head>',(f'<link rel="stylesheet" href="{base}/{file}">' if kind=='css' else f'<script defer src="{base}/{file}"></script>')+'</head>')
 title=t('Winter Cup для компаний и организаций — 22 января 2027','Winter Cup ettevõtetele ja organisatsioonidele — 22. jaanuar 2027','Winter Cup for companies and organisations — 22 January 2027')
 s=re.sub(r'<title>.*?</title>',f'<title>{title}</title>',s)
 s=re.sub(r'(<meta property="og:title" content=")[^"]*',lambda m:m[1]+esc(title),s)
 p.write_text(s)
print('Rendered business pages in RU, ET and EN')
